# The initial configuration file for apt-mirror-rsync. It is meant to
# live in /etc/apt. Tune the paths for your machines filesystem layout.
#
# File format: Don't use '=' or quotes.
# Lines are just: KEYWORD VALUE
# Spaces to align the text are OK

# RSYNC_CONFIG_DIR  Where the remote rsync mirrors config files are kept
#
# DIST_WORK_DIR     Temp work area for dist files before syncing.
#                   NOTE: This can require 50GB+ of disk space as each
#                   Ubuntu LTS release has approx 10GB of config files
#                   These temp files stay there so your SSD drive doesn't
#                   get worn out copying the same files each time.
#
# APT_MIRROR_DIR    Directory for the mirrored APT hosts
#                   e.g. the mirrored hosts in there could include:
#                       archive.ubuntu.com/
#                       security.ubuntu.com/
#                       ports.ubuntu.com/
#                       deb.debian.org/
#                       brave-browser-apt-release.s3.brave.com/
#
# LOGFILE           Where the log and debug output from apt-mirror-rsync is
#                   recorded. If it's large, it will be trimmed to the last
#                   10,000 lines on startup.
#
# FILE_OWNERSHIP    Who owns the repo metadata and deb files on this system
#                   Format is user:group
#
# KEEP_DEFAULT      How many version of a binary package should we keep?
#                   5 is a lot. 2 keeps the current version and one previous.
#                   Depending on the repo there can be one version or dozens.

DIST_WORK_DIR    /mirror/dist_temp
APT_MIRROR_DIR   /mirror/repos

RSYNC_CONFIG_DIR /etc/apt/sources.rsync.d
LOGFILE          /var/log/apt_mirror_rsync.log
FILE_OWNERSHIP   root:root
KEEP_DEFAULT     5
